server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: development
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://mysql:3306/manager_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
    username: root
    password: your_secure_password_here
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Taipei
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: false

logging:
  level:
    com.manager: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{20} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

info:
  app:
    name: Manager 系統
    description: Manager 系統後端 API
    version: 0.1.0
    java-version: 21
    spring-boot-version: 3.5.5

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:5173}
    allowed-methods:
      - GET
      - POST
    allowed-headers: "*"
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}