# Manager 系統 - 生產環境 Docker Compose (JAR 模式)
# 使用獨立端口避免與開發環境衝突

version: '3.8'

services:
  # 後端 API 服務
  manager-backend:
    image: eclipse-temurin:21-jre-alpine
    container_name: manager-backend
    restart: always
    working_dir: /app
    command: ["java", "-jar", "/app/manager-backend-0.1.0.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_PRIMARY_JDBC_URL=jdbc:mysql://manager-mysql:3306/manager_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
      - SPRING_DATASOURCE_PRIMARY_USERNAME=${MYSQL_APP_USER:-manager_user}
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=${MYSQL_APP_PASSWORD:-manager_secure_password}
      - SPRING_DATASOURCE_PRIMARY_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_REVIEWS_JDBC_URL=jdbc:mysql://manager-mysql:3306/manager_reviews_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
      - SPRING_DATASOURCE_REVIEWS_USERNAME=${MYSQL_APP_USER:-manager_user}
      - SPRING_DATASOURCE_REVIEWS_PASSWORD=${MYSQL_APP_PASSWORD:-manager_secure_password}
      - SPRING_DATASOURCE_REVIEWS_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SERVER_PORT=8080
      - MANAGEMENT_SERVER_PORT=8081
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_MANAGER=INFO

    ports:
      - "${BACKEND_PORT:-8082}:8080"
      - "${BACKEND_MGMT_PORT:-8083}:8081"

    volumes:
      - ./java/manager-backend-0.1.0.jar:/app/manager-backend-0.1.0.jar:ro
      - backend-logs:/app/logs

    networks:
      - manager-network

    depends_on:
      manager-mysql:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MySQL 資料庫服務
  manager-mysql:
    image: mysql:9.4.0
    container_name: manager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-test_root_123}
      MYSQL_USER: ${MYSQL_USER:-manager}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-manager123}
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password

    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+08:00'
      --max_allowed_packet=128M
      --innodb-buffer-pool-size=512M

    ports:
      - "${MYSQL_PORT:-3306}:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql/conf.d
      - ./mysql/init-data:/docker-entrypoint-initdb.d:ro

    networks:
      - manager-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# 網路配置
networks:
  manager-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

# Volume 配置
volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume/mysql

  mysql-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume/mysql-config

  backend-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volume/backend-logs