version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bench-mysql
    restart: unless-stopped
    ports:
      - "3380:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-benchdb}
      MYSQL_USER: ${MYSQL_USER:-benchuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-benchpass}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - mysql-network
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local

networks:
  mysql-network:
    driver: bridge