package shared.constant;

/** 錯誤碼定義 - 符合設計文件規範 */
public enum ErrorCode {
  SUCCESS("SUCCESS", "操作成功"),
  VALIDATION_ERROR("VALIDATION_ERROR", "資料驗證失敗"),
  PRODUCTION_NOT_FOUND("PRODUCTION_NOT_FOUND", "製作記錄不存在"),
  PRODUCTION_ALREADY_COMPLETED("PRODUCTION_ALREADY_COMPLETED", "製作記錄已完成"),
  INVALID_PRODUCTION_STATUS("INVALID_PRODUCTION_STATUS", "製作記錄狀態無效"),
  INVALID_LOG_TYPE("INVALID_LOG_TYPE", "無效的記錄類型"),
  DUPLICATE_BATCH_NUMBER("DUPLICATE_BATCH_NUMBER", "批次編號重複"),
  DATABASE_ERROR("DATABASE_ERROR", "資料庫操作失敗"),
  MISSING_REQUIRED_FIELD("MISSING_REQUIRED_FIELD", "缺少必要欄位"),
  INVALID_DATA_FORMAT("INVALID_DATA_FORMAT", "資料格式錯誤"),

  // 1.1.2 評估功能相關錯誤碼
  EVALUATION_NOT_FOUND("EVALUATION_NOT_FOUND", "評估記錄不存在"),
  EVALUATION_ALREADY_EXISTS("EVALUATION_ALREADY_EXISTS", "該製作記錄已存在評估"),
  INVALID_SCORE_RANGE("INVALID_SCORE_RANGE", "評分超出有效範圍(1-5)"),
  PRODUCTION_NOT_COMPLETED("PRODUCTION_NOT_COMPLETED", "製作記錄尚未完成"),

  // 1.1.4 配方管理相關錯誤碼
  // 配方查詢錯誤
  RECIPE_NOT_FOUND("RECIPE_NOT_FOUND", "配方不存在"),
  RECIPE_ACCESS_DENIED("RECIPE_ACCESS_DENIED", "配方存取權限不足"),
  INVALID_RECIPE_PARAMS("INVALID_RECIPE_PARAMS", "查詢參數無效"),

  // 配方管理錯誤
  RECIPE_NAME_EXISTS("RECIPE_NAME_EXISTS", "配方名稱已存在"),
  RECIPE_CREATE_FAILED("RECIPE_CREATE_FAILED", "配方建立失敗"),
  RECIPE_UPDATE_FAILED("RECIPE_UPDATE_FAILED", "配方更新失敗"),
  RECIPE_DELETE_FAILED("RECIPE_DELETE_FAILED", "配方刪除失敗"),
  RECIPE_HAS_PRODUCTIONS("RECIPE_HAS_PRODUCTIONS", "配方已被使用，無法刪除"),

  // 資料驗證錯誤
  INVALID_RECIPE_NAME("INVALID_RECIPE_NAME", "配方名稱格式無效"),
  INVALID_TEMPERATURE("INVALID_TEMPERATURE", "溫度數值無效"),
  INVALID_TIME("INVALID_TIME", "時間數值無效"),
  MISSING_INGREDIENTS("MISSING_INGREDIENTS", "缺少食材資料"),
  MISSING_STEPS("MISSING_STEPS", "缺少步驟資料"),
  INVALID_INGREDIENT_DATA("INVALID_INGREDIENT_DATA", "食材資料格式無效"),
  INVALID_STEP_DATA("INVALID_STEP_DATA", "步驟資料格式無效"),
  INVALID_AMOUNT("INVALID_AMOUNT", "用量數值無效"),
  INVALID_STEP_SEQUENCE("INVALID_STEP_SEQUENCE", "步驟編號不連續或重複"),
  RECIPE_DATA_TOO_LARGE("RECIPE_DATA_TOO_LARGE", "配方資料過大"),

  // 通用錯誤碼（重新組織）
  VALIDATION_REQUIRED("VALIDATION_REQUIRED", "必填欄位缺失"),
  VALIDATION_LENGTH("VALIDATION_LENGTH", "欄位長度超出限制"),
  VALIDATION_FORMAT("VALIDATION_FORMAT", "資料格式錯誤"),
  BUSINESS_REFERENCE_EXISTS("BUSINESS_REFERENCE_EXISTS", "資料被其他記錄引用"),
  BUSINESS_NOT_FOUND("BUSINESS_NOT_FOUND", "資料不存在"),
  BUSINESS_DUPLICATE_WARNING("BUSINESS_DUPLICATE_WARNING", "資料重複警告");

  private final String code;
  private final String message;

  ErrorCode(String code, String message) {
    this.code = code;
    this.message = message;
  }

  public String getCode() {
    return code;
  }

  public String getMessage() {
    return message;
  }
}
