global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'cloud-server-benchmark'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - 所有節點的系統監控
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets:
          - '13.233.122.195:9100'   # bench-1
          - '13.203.23.144:9100'    # bench-2
          - '65.0.106.33:9100'      # test
        labels:
          service: 'node-exporter'


  # Blackbox Exporter - 網路探測
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 30s
    static_configs:
      - targets:
          - http://13.233.122.195    # bench-1
          - http://13.203.23.144     # bench-2
          - http://65.0.106.33       # test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    scrape_interval: 30s
    static_configs:
      - targets:
          - 13.233.122.195:22     # bench-1 SSH
          - 13.203.23.144:22      # bench-2 SSH
          - 65.0.106.33:22        # test SSH
          - 13.233.122.195:3306   # bench-1 MySQL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 30s
    static_configs:
      - targets:
          - 13.233.122.195        # bench-1
          - 13.203.23.144         # bench-2
          - 65.0.106.33           # test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115