global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'cloud-server-benchmark'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - 所有節點的系統監控
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets:
          - '3.108.252.22:9100'   # bench-1
          - '65.0.5.177:9100'     # test
          # - 'bench-2-ip:9100'   # bench-2 暫時沒有
        labels:
          service: 'node-exporter'


  # Blackbox Exporter - 網路探測
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scrape_interval: 30s
    static_configs:
      - targets:
          - http://3.108.252.22    # bench-1
          - http://65.0.5.177      # test
          # - http://bench-2-ip    # bench-2 暫時沒有
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    scrape_interval: 30s
    static_configs:
      - targets:
          - 3.108.252.22:22     # bench-1 SSH
          - 65.0.5.177:22       # test SSH
          # - bench-2-ip:22     # bench-2 暫時沒有
          - 3.108.252.22:3306   # bench-1 MySQL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 30s
    static_configs:
      - targets:
          - 3.108.252.22        # bench-1
          - 65.0.5.177          # test
          # - bench-2-ip        # bench-2 暫時沒有
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115